### ISSUE TITLE
requesting an improved scala theme

### ISSUE THREAD

**Issue by krishna81m** [jnurmine/Zenburn#17]
Having used Zenburn since it was released, and given scala's popularity, it makes sense to improve scala support as there is not a single decent Eclipse dark color theme for Scala.

http://stackoverflow.com/search?q=eclipse+dark+theme+scala+
https://github.com/chriskempson/tomorrow-theme

**Comment by jnurmine** [comment]
Let's hope someone picks this up and makes it happen...
I can't do it myself, I don't use Scala nor Eclipse.
