### ISSUE TITLE
Terminal field hasn't been set?

### ISSUE THREAD

**Issue by com3345** [jnurmine/Zenburn#21]
Since VIM8 introduced the terminal mode, I searched in the zenburn.vim, there's no field called Terminal

Wish we could get one, maybe higher contrast than current setting in order to distinguish the terminal from normal windows.

P.S. Although it's ugly and not harmony with the current part, the example setting in terminal.txt tells the difference between terminal mode and normal mode
<img width="1138" alt="2018-04-29 7 44 36" src="https://user-images.githubusercontent.com/11958810/39401793-325159c6-4b81-11e8-866a-59869ae6de52.png">

**Comment by jnurmine** [comment]
You are right, thanks for reporting this. I'll add a fix. The highlight for Terminal is a bit limited but it can certainly be made better than blue on light gray.
