### ISSUE TITLE
Make comments italic in terminal

### ISSUE THREAD

**Issue by neezer** [jnurmine/Zenburn#26]
```diff
- hi Comment         guifg=#7f9f7f gui=italic                   ctermfg=108
+ hi Comment         guifg=#7f9f7f gui=italic                   ctermfg=108 cterm=italic
```

... ?? (to appease OperatorMono & Terminal users like me. 😄)

**Comment by jnurmine** [comment]
Thanks, good idea! In some terminals (e.g. mine) the terminal italic doesn't quite work. For example:

```
echo -e "\e[3m test \e[23m"
```
is not italicized. However, since this works for some people, I added a new configuration variable. It works like this:

```
let g:zenburn_italic_Comment=1
colors zenburn
```

The default behaviour is to use the old non-italic Comment.
