### ISSUE TITLE
What's this font family in screenshot?

### ISSUE THREAD

**Issue by richellyitalo** [jnurmine/Zenburn#32]
What's this font family in screenshot?

**Comment by jnurmine** [comment]
Hi, it was probably "Andale Mono", 9 pt. Or "Monospace", 9 pt. It's a rather old picture.

Nowadays I use "Fantasque Sans Mono" at 10 pt.

**Comment by jnurmine** [comment]
Scratch that, it's not Monospace, the "p" looks different. It's Andale Mono.

**Comment by richellyitalo** [comment]
Thanks! I really appreciate your attention @jnurmine .
And congrats for this color scheme!

**Comment by jnurmine** [comment]
No worries!
