### ISSUE TITLE
Does Zenburn work better in terms of syntax highlighting with vim-polyglot?

### ISSUE THREAD

**Issue by HicaroD** [jnurmine/Zenburn#35]
I'm currently using Zenburn as my main colorscheme, but I have vim-polyglot installed and I'm not sure if vim-polyglot improves the syntax highlighting.

**Comment by jnurmine** [comment]
Hi, I don't use vim-polyglot myself (simply haven't had a need), but as I've understood it's a collection of various language/filetype syntax highlighting definitions.

Now, the syntax highlighting definitions in Vim work by parsing certain language-specific patterns and linking these with built-in Vim syntax groups, e.g. Constant, Comment, Enum and so on. The colour schemes contain colouring instructions for each such group. Thus the vim-polyglot definitions should work with any colorscheme, including Zenburn.

Whether Zenburn itself works better, no, not really -- however, you'll get more languages/filetypes supported and coloured with Zenburn colors when using vim-polyglot. (If Vim cannot recognize the filetype and parse the language/type-specific tags, it won't be able to colorize it properly)

Does this answer your question?

**Comment by HicaroD** [comment]
Yeah, gotcha. Thanks for answering! I'll be closing the issue
