### ISSUE TITLE
Cannot install it after updating phpstorm 2023.3.1

### ISSUE THREAD

**Issue by khakimjanovich** [jnurmine/Zenburn#37]
![image](https://github.com/jnurmine/Zenburn/assets/37039084/1ed87ece-15ba-4860-b169-6a28e4c1f8c9)

**Comment by jnurmine** [comment]
Sorry, I can't help you with this, this project is a Vim color scheme.

Probably the IntelliJ theme isn't updated yet, so I recommend to file an issue at the IntelliJ theme instead: https://github.com/smashedtoatoms/zenburn
